@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Card API 3.0.+ (2026-04-21)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "card" as card {

' SPI
package "spi" as spi {
    interface "CardSelectionExtensionSpi" as CardSelectionExtensionSpi <<red>> {
        +getCardSelectionRequest() → CardSelectionRequestSpi
        +parse(cardSelectionResponseApi: CardSelectionResponseApi) → SmartCardSpi
        {method} <size:10><color:#7F8C8D>    ⚠ errors: Parse</color></size>
    }
    interface SmartCardSpi <<red>> {
        +<color:blue>deactivate() → Unit
    }
    interface "<color:blue>MultichannelSmartCardSpi" as MultichannelSmartCardSpi <<red>> extends SmartCardSpi {
        +<color:blue>getChannel() → Int
    }
    ' REQUEST
    interface CardSelectionRequestSpi <<red>> {
        +getSuccessfulSelectionStatusWords() → Set<Int>
        +getCardRequest() → CardRequestSpi?
    }
    interface CardRequestSpi <<red>> {
        +getApduRequests() → List<ApduRequestSpi>
        +stopOnUnsuccessfulStatusWord() → Boolean
    }
    interface ApduRequestSpi <<red>> {
        +getApdu() → ByteArray
        +getSuccessfulStatusWords() → Set<Int>
        +getInfo() → String?
        +<color:blue>getApduExchangeMaxDuration() → Long?
    }
}
class "**final** CardApiProperties" as ApiProperties <<green>> {
    +{static} **final** VERSION: String
}
exception "Parse" as Parse <<green>> <<error>> {
    +val message: String
    +val cause: Any?
}
interface ProxyReaderApi {
    --
    +<color:blue>transmitCardRequest(
        \t<color:blue>cardRequest: CardRequestSpi,
        \t<color:blue>smartCard: SmartCardSpi) → CardResponseApi
    {method} <size:10><color:#7F8C8D>    ⚠ errors: ReaderBrokenCommunication, CardBrokenCommunication, UnexpectedStatusWord, ApduExchangeDurationExceeded</color></size>

    +<color:blue>transmitCardRequestAndCloseChannel(
        \t<color:blue>cardRequest: CardRequestSpi,
        \t<color:blue>multichannelSmartCard: MultichannelSmartCardSpi) → CardResponseApi
    {method} <size:10><color:#7F8C8D>    ⚠ errors: ReaderBrokenCommunication, CardBrokenCommunication, UnexpectedStatusWord, ApduExchangeDurationExceeded</color></size>

    +<color:blue>closeChannel(multichannelSmartCard: MultichannelSmartCardSpi) → Unit
    {method} <size:10><color:#7F8C8D>    ⚠ errors: ReaderBrokenCommunication, CardBrokenCommunication</color></size>
}
' RESPONSE
interface CardSelectionResponseApi {
    +<color:blue>getChannel() → Int
    +getPowerOnData() → String?
    +getSelectApplicationResponse() → ApduResponseApi?
    +hasMatched() → Boolean
    +getCardResponse() → CardResponseApi?
}
interface "<<Serializable>>\nCardResponseApi" as CardResponseApi {
    +getApduResponses() → List<ApduResponseApi>
}
interface "<<Serializable>>\nApduResponseApi" as ApduResponseApi {
    +getApdu() → ByteArray
    +getDataOut() → ByteArray
    +getStatusWord() → Int
    +<color:blue>getApduExchangeDuration() → Long?
}

exception "ReaderBrokenCommunication\nCardBrokenCommunication\nUnexpectedStatusWord\n<color:blue>ApduExchangeDurationExceeded" as errors <<green>> <<error>> {
    +val message: String
    +val cause: Any?
    +val cardResponse: CardResponseApi?
    +val isCardResponseComplete: Boolean
}

}

' Associations

CardSelectionExtensionSpi ..> SmartCardSpi #C_LINK : provide >
CardSelectionExtensionSpi ..> CardSelectionRequestSpi #C_LINK : provide >
CardSelectionExtensionSpi ..> CardSelectionResponseApi #C_USE : use >

CardSelectionRequestSpi ..> CardRequestSpi #C_LINK : provide >

CardRequestSpi ..> ApduRequestSpi #C_LINK : provide >

CardSelectionResponseApi ..> ApduResponseApi #C_LINK : provide >
CardSelectionResponseApi ..> CardResponseApi #C_LINK : provide >

CardResponseApi ..> ApduResponseApi #C_LINK : provide >

errors *-up- "0..1" CardResponseApi #C_LINK

ProxyReaderApi .left.> CardRequestSpi #C_USE : use >
ProxyReaderApi .up.> SmartCardSpi #C_USE : use >
ProxyReaderApi .left.> MultichannelSmartCardSpi #C_USE : use >

ProxyReaderApi .right.> CardResponseApi #C_LINK : provide >

' == LAYOUT ==

ApiProperties -[hidden]- Parse

' == STYLE ==

package card #C_GREY1 {}
package card.spi #C_GREY2 {}

@enduml