name: Publish Specification - RELEASE

on:
  release:
    types: [published]

jobs:
  publish-release:
    uses: calypsonet/calypsonet-actions/.github/workflows/reusable-publish-spec-release.yml@main # NOSONAR - Same organization, trusted source
    secrets: inherit # NOSONAR - Same organization, trusted source
