name: Publish Calypsonet Terminal Calypso API - UML class diagrams to GH pages

on:
  push:
    branches:
      - main

jobs:
  publish-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Update permissions
        working-directory: .
        run: chmod +x ./.github/scripts/*.sh
      - name: Prepare publication locally
        working-directory: .
        run: ./.github/scripts/prepare_publication.sh
      - name: Deploy diagrams to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
